use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ec2InstanceEvent {
    pub instance_id: String,
    pub event_type: String,
    pub region: String,
    pub availability_zone: String,
    pub instance_type: String,
    pub image_id: String,
    pub state: String,
    pub launch_time: DateTime<Utc>,
    pub private_ip: String,
    pub public_ip: Option<String>,
    pub vpc_id: String,
    pub subnet_id: String,
    pub security_groups: Vec<String>,
    pub iam_role: Option<String>,
    pub tags: HashMap<String, String>,
    pub cpu_utilization: Option<f64>,
    pub memory_utilization: Option<f64>,
    pub network_in_bytes: Option<i64>,
    pub network_out_bytes: Option<i64>,
    pub ebs_volumes: Vec<serde_json::Value>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub tenancy: String,
    pub platform: Option<String>,
    pub monitoring_state: String,
    pub auto_scaling_group: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct S3BucketEvent {
    pub bucket_name: String,
    pub event_type: String,
    pub region: String,
    pub object_key: String,
    pub object_size: i64,
    pub etag: String,
    pub version_id: Option<String>,
    pub storage_class: String,
    pub content_type: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub requester_id: String,
    pub source_ip: String,
    pub request_id: String,
    pub is_delete_marker: bool,
    pub encryption_type: Option<String>,
    pub replication_status: Option<String>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub access_control_list: Vec<serde_json::Value>,
    pub lifecycle_rule: Option<String>,
    pub cors_rules: Vec<serde_json::Value>,
    pub transfer_acceleration: bool,
    pub object_lock_mode: Option<String>,
    pub legal_hold: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LambdaInvocationEvent {
    pub function_name: String,
    pub function_version: String,
    pub invocation_type: String,
    pub request_id: String,
    pub region: String,
    pub runtime: String,
    pub handler: String,
    pub memory_size_mb: i64,
    pub timeout_seconds: i64,
    pub duration_ms: f64,
    pub billed_duration_ms: i64,
    pub max_memory_used_mb: i64,
    pub init_duration_ms: Option<f64>,
    pub timestamp: DateTime<Utc>,
    pub status_code: i64,
    pub error_type: Option<String>,
    pub error_message: Option<String>,
    pub log_group: String,
    pub log_stream: String,
    pub tracing_header: Option<String>,
    pub environment_variables: HashMap<String, String>,
    pub layers: Vec<String>,
    pub cold_start: bool,
    pub concurrency_limit: Option<i64>,
    pub dead_letter_queue: Option<String>,
    pub event_source_arn: Option<String>,
    pub tags: HashMap<String, String>,
    pub vpc_config: Option<serde_json::Value>,
    pub provisioned_concurrency: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CloudWatchAlarmEvent {
    pub alarm_name: String,
    pub alarm_arn: String,
    pub alarm_description: Option<String>,
    pub state_value: String,
    pub previous_state_value: String,
    pub state_reason: String,
    pub state_updated_timestamp: DateTime<Utc>,
    pub metric_name: String,
    pub namespace: String,
    pub statistic: String,
    pub period: i64,
    pub threshold: f64,
    pub comparison_operator: String,
    pub evaluation_periods: i64,
    pub datapoints_to_alarm: i64,
    pub treat_missing_data: String,
    pub region: String,
    pub account_id: String,
    pub dimensions: HashMap<String, String>,
    pub actions_enabled: bool,
    pub ok_actions: Vec<String>,
    pub alarm_actions: Vec<String>,
    pub insufficient_data_actions: Vec<String>,
    pub unit: Option<String>,
    pub extended_statistic: Option<String>,
    pub tags: HashMap<String, String>,
    pub anomaly_detector_config: Option<serde_json::Value>,
    pub metrics_insights_query: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RdsEvent {
    pub db_instance_id: String,
    pub event_type: String,
    pub engine: String,
    pub engine_version: String,
    pub db_instance_class: String,
    pub allocated_storage_gb: i64,
    pub region: String,
    pub availability_zone: String,
    pub multi_az: bool,
    pub status: String,
    pub endpoint_address: Option<String>,
    pub endpoint_port: i64,
    pub master_username: String,
    pub db_name: Option<String>,
    pub vpc_id: Option<String>,
    pub storage_type: String,
    pub iops: Option<i64>,
    pub storage_encrypted: bool,
    pub kms_key_id: Option<String>,
    pub backup_retention_period: i64,
    pub preferred_backup_window: String,
    pub preferred_maintenance_window: String,
    pub latest_restorable_time: Option<DateTime<Utc>>,
    pub cpu_utilization: Option<f64>,
    pub free_storage_bytes: Option<i64>,
    pub connections_count: Option<i64>,
    pub read_iops: Option<f64>,
    pub write_iops: Option<f64>,
    pub replica_lag_seconds: Option<f64>,
    pub tags: HashMap<String, String>,
    pub parameter_groups: Vec<serde_json::Value>,
    pub security_groups: Vec<String>,
    pub timestamp: DateTime<Utc>,
    pub performance_insights_enabled: bool,
    pub deletion_protection: bool,
    pub auto_minor_version_upgrade: bool,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EcsTaskEvent {
    pub task_arn: String,
    pub cluster_arn: String,
    pub task_definition_arn: String,
    pub container_instance_arn: Option<String>,
    pub launch_type: String,
    pub desired_status: String,
    pub last_status: String,
    pub started_at: Option<DateTime<Utc>>,
    pub stopped_at: Option<DateTime<Utc>>,
    pub stopping_reason: Option<String>,
    pub started_by: Option<String>,
    pub group: Option<String>,
    pub region: String,
    pub availability_zone: Option<String>,
    pub cpu: String,
    pub memory: String,
    pub platform_version: Option<String>,
    pub connectivity: Option<String>,
    pub health_status: String,
    pub containers: Vec<serde_json::Value>,
    pub attachments: Vec<serde_json::Value>,
    pub tags: HashMap<String, String>,
    pub overrides: Option<serde_json::Value>,
    pub network_configuration: Option<serde_json::Value>,
    pub enable_execute_command: bool,
    pub ephemeral_storage_gb: Option<i64>,
    pub pull_started_at: Option<DateTime<Utc>>,
    pub pull_stopped_at: Option<DateTime<Utc>>,
    pub timestamp: DateTime<Utc>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SqsMessageEvent {
    pub message_id: String,
    pub queue_url: String,
    pub queue_name: String,
    pub region: String,
    pub body: String,
    pub body_md5: String,
    pub sent_timestamp: DateTime<Utc>,
    pub approximate_receive_count: i64,
    pub approximate_first_receive_timestamp: Option<DateTime<Utc>>,
    pub sender_id: String,
    pub message_group_id: Option<String>,
    pub message_deduplication_id: Option<String>,
    pub sequence_number: Option<String>,
    pub delay_seconds: i64,
    pub visibility_timeout_seconds: i64,
    pub message_attributes: HashMap<String, serde_json::Value>,
    pub system_attributes: HashMap<String, String>,
    pub is_fifo: bool,
    pub content_based_deduplication: bool,
    pub dead_letter_queue_arn: Option<String>,
    pub redrive_count: Option<i64>,
    pub encryption_type: Option<String>,
    pub kms_key_id: Option<String>,
    pub tags: HashMap<String, String>,
    pub event_source_arn: Option<String>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SnsNotificationEvent {
    pub notification_id: String,
    pub topic_arn: String,
    pub topic_name: String,
    pub region: String,
    pub subject: Option<String>,
    pub message: String,
    pub message_id: String,
    pub timestamp: DateTime<Utc>,
    pub message_structure: Option<String>,
    pub signing_cert_url: Option<String>,
    pub signature: Option<String>,
    pub signature_version: String,
    pub subscription_arn: Option<String>,
    pub token: Option<String>,
    pub notification_type: String,
    pub unsubscribe_url: Option<String>,
    pub message_attributes: HashMap<String, serde_json::Value>,
    pub is_fifo: bool,
    pub content_based_deduplication: bool,
    pub message_group_id: Option<String>,
    pub message_deduplication_id: Option<String>,
    pub delivery_policy: Option<serde_json::Value>,
    pub filter_policy: Option<serde_json::Value>,
    pub redrive_policy: Option<serde_json::Value>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub protocol: String,
    pub endpoint: Option<String>,
    pub effective_delivery_policy: Option<serde_json::Value>,
}
