use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderEvent {
    pub order_id: String,
    pub customer_id: String,
    pub customer_email: String,
    pub status: String,
    pub currency: String,
    pub subtotal: f64,
    pub tax_amount: f64,
    pub shipping_amount: f64,
    pub discount_amount: f64,
    pub total_amount: f64,
    pub payment_method: String,
    pub payment_status: String,
    pub billing_address: serde_json::Value,
    pub shipping_address: serde_json::Value,
    pub line_items: Vec<serde_json::Value>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub completed_at: Option<DateTime<Utc>>,
    pub cancelled_at: Option<DateTime<Utc>>,
    pub shipping_method: String,
    pub tracking_number: Option<String>,
    pub notes: Option<String>,
    pub source_channel: String,
    pub referral_code: Option<String>,
    pub coupon_codes: Vec<String>,
    pub is_gift: bool,
    pub gift_message: Option<String>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub tags: HashMap<String, String>,
    pub custom_attributes: HashMap<String, serde_json::Value>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub weight_kg: Option<f64>,
    pub estimated_delivery_date: Option<DateTime<Utc>>,
    pub warehouse_id: Option<String>,
    pub fulfillment_status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShipmentEvent {
    pub shipment_id: String,
    pub order_id: String,
    pub carrier: String,
    pub carrier_service: String,
    pub tracking_number: String,
    pub tracking_url: Option<String>,
    pub status: String,
    pub shipped_at: Option<DateTime<Utc>>,
    pub delivered_at: Option<DateTime<Utc>>,
    pub estimated_delivery_date: Option<DateTime<Utc>>,
    pub actual_delivery_date: Option<DateTime<Utc>>,
    pub origin_address: serde_json::Value,
    pub destination_address: serde_json::Value,
    pub weight_kg: f64,
    pub dimensions_cm: serde_json::Value,
    pub shipping_cost: f64,
    pub insurance_cost: Option<f64>,
    pub currency: String,
    pub items: Vec<serde_json::Value>,
    pub package_count: i64,
    pub signature_required: bool,
    pub is_return: bool,
    pub label_url: Option<String>,
    pub customs_info: Option<serde_json::Value>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub events: Vec<serde_json::Value>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub warehouse_id: String,
    pub batch_id: Option<String>,
    pub delivery_instructions: Option<String>,
    pub notification_email: Option<String>,
    pub notification_sms: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InventoryChangeEvent {
    pub id: String,
    pub sku: String,
    pub product_id: String,
    pub product_name: String,
    pub variant_id: Option<String>,
    pub warehouse_id: String,
    pub location_bin: Option<String>,
    pub change_type: String,
    pub quantity_before: i64,
    pub quantity_after: i64,
    pub quantity_delta: i64,
    pub reason: String,
    pub reference_type: Option<String>,
    pub reference_id: Option<String>,
    pub unit_cost: f64,
    pub total_value_change: f64,
    pub currency: String,
    pub performed_by: String,
    pub timestamp: DateTime<Utc>,
    pub lot_number: Option<String>,
    pub expiry_date: Option<DateTime<Utc>>,
    pub serial_numbers: Vec<String>,
    pub is_adjustment: bool,
    pub approval_status: Option<String>,
    pub approved_by: Option<String>,
    pub notes: Option<String>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub supplier_id: Option<String>,
    pub purchase_order_id: Option<String>,
    pub receiving_document_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReturnEvent {
    pub return_id: String,
    pub order_id: String,
    pub customer_id: String,
    pub customer_email: String,
    pub status: String,
    pub return_type: String,
    pub reason_code: String,
    pub reason_description: Option<String>,
    pub items: Vec<serde_json::Value>,
    pub refund_amount: f64,
    pub restocking_fee: Option<f64>,
    pub return_shipping_cost: Option<f64>,
    pub currency: String,
    pub refund_method: String,
    pub refund_status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub received_at: Option<DateTime<Utc>>,
    pub refunded_at: Option<DateTime<Utc>>,
    pub return_label_url: Option<String>,
    pub tracking_number: Option<String>,
    pub carrier: Option<String>,
    pub warehouse_id: Option<String>,
    pub quality_inspection_status: Option<String>,
    pub quality_inspection_notes: Option<String>,
    pub is_exchange: bool,
    pub exchange_order_id: Option<String>,
    pub customer_notes: Option<String>,
    pub internal_notes: Option<String>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub photos: Vec<String>,
    pub condition: Option<String>,
    pub resolution: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewEvent {
    pub review_id: String,
    pub product_id: String,
    pub product_name: String,
    pub variant_id: Option<String>,
    pub order_id: Option<String>,
    pub customer_id: String,
    pub customer_name: Option<String>,
    pub customer_email: Option<String>,
    pub rating: f64,
    pub title: Option<String>,
    pub body: Option<String>,
    pub status: String,
    pub verified_purchase: bool,
    pub helpful_votes: i64,
    pub not_helpful_votes: i64,
    pub report_count: i64,
    pub response: Option<String>,
    pub response_by: Option<String>,
    pub response_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub published_at: Option<DateTime<Utc>>,
    pub media_urls: Vec<String>,
    pub pros: Vec<String>,
    pub cons: Vec<String>,
    pub tags: HashMap<String, String>,
    pub sentiment_score: Option<f64>,
    pub language: Option<String>,
    pub source_platform: String,
    pub metadata: HashMap<String, serde_json::Value>,
    pub custom_attributes: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CouponEvent {
    pub coupon_id: String,
    pub code: String,
    pub name: String,
    pub description: Option<String>,
    pub discount_type: String,
    pub discount_value: f64,
    pub currency: Option<String>,
    pub minimum_order_amount: Option<f64>,
    pub maximum_discount_amount: Option<f64>,
    pub usage_limit: Option<i64>,
    pub usage_count: i64,
    pub usage_limit_per_customer: Option<i64>,
    pub is_active: bool,
    pub starts_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub applicable_products: Vec<String>,
    pub applicable_categories: Vec<String>,
    pub excluded_products: Vec<String>,
    pub excluded_categories: Vec<String>,
    pub customer_eligibility: String,
    pub eligible_customer_ids: Vec<String>,
    pub first_order_only: bool,
    pub combinable: bool,
    pub auto_apply: bool,
    pub channel_restrictions: Vec<String>,
    pub region_restrictions: Vec<String>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub created_by: String,
    pub campaign_id: Option<String>,
    pub total_discount_given: f64,
    pub average_order_value: Option<f64>,
    pub conversion_rate: Option<f64>,
}
