use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CsvTransactionRow {
    pub transaction_id: String,
    pub account_id: String,
    pub counterparty_id: Option<String>,
    pub amount: f64,
    pub currency: String,
    pub transaction_type: String,
    pub status: String,
    pub description: Option<String>,
    pub reference: Option<String>,
    pub category: String,
    pub subcategory: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub settled_at: Option<DateTime<Utc>>,
    pub merchant_name: Option<String>,
    pub merchant_category_code: Option<String>,
    pub balance_after: f64,
    pub fee_amount: Option<f64>,
    pub exchange_rate: Option<f64>,
    pub original_amount: Option<f64>,
    pub original_currency: Option<String>,
    pub metadata: HashMap<String, String>,
    pub tags: Vec<String>,
    pub is_recurring: bool,
    pub risk_score: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CsvInventoryRow {
    pub sku: String,
    pub product_name: String,
    pub category: String,
    pub subcategory: Option<String>,
    pub quantity_on_hand: i64,
    pub quantity_reserved: i64,
    pub quantity_available: i64,
    pub reorder_point: i64,
    pub reorder_quantity: i64,
    pub unit_cost: f64,
    pub unit_price: f64,
    pub currency: String,
    pub warehouse_id: String,
    pub warehouse_zone: Option<String>,
    pub location_bin: Option<String>,
    pub supplier_id: String,
    pub supplier_name: String,
    pub last_received_at: Option<DateTime<Utc>>,
    pub last_counted_at: Option<DateTime<Utc>>,
    pub weight_kg: Option<f64>,
    pub dimensions: Option<String>,
    pub is_active: bool,
    pub is_hazardous: bool,
    pub lot_number: Option<String>,
    pub expiry_date: Option<DateTime<Utc>>,
    pub tags: Vec<String>,
    pub custom_attributes: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CsvUserActivityRow {
    pub event_id: String,
    pub user_id: String,
    pub session_id: String,
    pub event_type: String,
    pub page_url: Option<String>,
    pub referrer_url: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub duration_ms: Option<i64>,
    pub ip_address: String,
    pub user_agent: String,
    pub device_type: String,
    pub os_name: String,
    pub browser_name: String,
    pub screen_resolution: Option<String>,
    pub viewport_size: Option<String>,
    pub country_code: Option<String>,
    pub region: Option<String>,
    pub city: Option<String>,
    pub utm_source: Option<String>,
    pub utm_medium: Option<String>,
    pub utm_campaign: Option<String>,
    pub custom_properties: HashMap<String, serde_json::Value>,
    pub is_authenticated: bool,
    pub ab_test_variants: HashMap<String, String>,
    pub feature_flags: Vec<String>,
    pub performance_metrics: Option<serde_json::Value>,
}
