use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomJsonEvent {
    pub id: String,
    pub source: String,
    pub event_type: String,
    pub payload: serde_json::Value,
    pub timestamp: DateTime<Utc>,
    pub schema_version: String,
    pub correlation_id: Option<String>,
    pub metadata: HashMap<String, serde_json::Value>,
    pub tags: Vec<String>,
    pub priority: i64,
    pub ttl_seconds: Option<i64>,
    pub idempotency_key: Option<String>,
    pub callback_url: Option<String>,
    pub headers: HashMap<String, String>,
    pub retry_count: i64,
    pub max_retries: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlertEvent {
    pub id: String,
    pub alert_name: String,
    pub severity: String,
    pub source: String,
    pub message: String,
    pub description: Option<String>,
    pub triggered_at: DateTime<Utc>,
    pub resolved_at: Option<DateTime<Utc>>,
    pub acknowledged_at: Option<DateTime<Utc>>,
    pub acknowledged_by: Option<String>,
    pub status: String,
    pub labels: HashMap<String, String>,
    pub annotations: HashMap<String, String>,
    pub fingerprint: String,
    pub generator_url: Option<String>,
    pub dashboard_url: Option<String>,
    pub runbook_url: Option<String>,
    pub previous_severity: Option<String>,
    pub escalation_level: i64,
    pub notification_channels: Vec<String>,
    pub related_alerts: Vec<String>,
    pub affected_resources: Vec<serde_json::Value>,
    pub threshold_value: Option<f64>,
    pub current_value: Option<f64>,
    pub evaluation_period_seconds: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricEvent {
    pub id: String,
    pub metric_name: String,
    pub namespace: String,
    pub value: f64,
    pub unit: String,
    pub timestamp: DateTime<Utc>,
    pub dimensions: HashMap<String, String>,
    pub tags: Vec<String>,
    pub aggregation_type: String,
    pub period_seconds: i64,
    pub min_value: Option<f64>,
    pub max_value: Option<f64>,
    pub sum_value: Option<f64>,
    pub count: i64,
    pub percentile_values: HashMap<String, f64>,
    pub source_host: String,
    pub source_region: String,
    pub source_environment: String,
    pub sample_rate: f64,
    pub is_monotonic: bool,
    pub statistical_values: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditEvent {
    pub id: String,
    pub actor_id: String,
    pub actor_email: String,
    pub actor_ip: String,
    pub actor_user_agent: String,
    pub action: String,
    pub resource_type: String,
    pub resource_id: String,
    pub resource_name: Option<String>,
    pub timestamp: DateTime<Utc>,
    pub result: String,
    pub reason: Option<String>,
    pub organization_id: String,
    pub project_id: Option<String>,
    pub session_id: String,
    pub request_id: String,
    pub changes: Option<serde_json::Value>,
    pub previous_state: Option<serde_json::Value>,
    pub new_state: Option<serde_json::Value>,
    pub geo_location: Option<serde_json::Value>,
    pub compliance_tags: Vec<String>,
    pub risk_score: Option<f64>,
    pub mfa_used: bool,
    pub api_version: String,
}
