use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PushEvent {
    pub id: String,
    pub ref_name: String,
    pub before: String,
    pub after: String,
    pub repository: String,
    pub pusher: String,
    pub created: bool,
    pub deleted: bool,
    pub forced: bool,
    pub commits: Vec<serde_json::Value>,
    pub head_commit: Option<serde_json::Value>,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PullRequestEvent {
    pub id: i64,
    pub action: String,
    pub number: i64,
    pub title: String,
    pub body: Option<String>,
    pub state: String,
    pub user: String,
    pub head_ref: String,
    pub base_ref: String,
    pub merged: bool,
    pub mergeable: Option<bool>,
    pub labels: Vec<String>,
    pub reviewers: Vec<String>,
    pub draft: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub repository: String,
    pub additions: i64,
    pub deletions: i64,
    pub changed_files: i64,
    pub commits_count: i64,
    pub comments_count: i64,
    pub review_comments_count: i64,
    pub milestone: Option<String>,
    pub assignees: Vec<String>,
    pub requested_teams: Vec<String>,
    pub auto_merge: Option<serde_json::Value>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IssueEvent {
    pub id: i64,
    pub action: String,
    pub number: i64,
    pub title: String,
    pub body: Option<String>,
    pub state: String,
    pub user: String,
    pub labels: Vec<String>,
    pub assignees: Vec<String>,
    pub milestone: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub closed_at: Option<DateTime<Utc>>,
    pub repository: String,
    pub comments_count: i64,
    pub is_pull_request: bool,
    pub locked: bool,
    pub reactions: HashMap<String, i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleaseEvent {
    pub id: i64,
    pub action: String,
    pub tag_name: String,
    pub name: Option<String>,
    pub body: Option<String>,
    pub draft: bool,
    pub prerelease: bool,
    pub author: String,
    pub target_commitish: String,
    pub created_at: DateTime<Utc>,
    pub published_at: Option<DateTime<Utc>>,
    pub assets: Vec<serde_json::Value>,
    pub repository: String,
    pub tarball_url: Option<String>,
    pub zipball_url: Option<String>,
    pub mentions_count: Option<i64>,
    pub discussion_url: Option<String>,
    pub reactions: HashMap<String, i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeploymentEvent {
    pub id: i64,
    pub action: String,
    pub environment: String,
    pub description: Option<String>,
    pub creator: String,
    pub ref_name: String,
    pub sha: String,
    pub task: String,
    pub payload: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub repository: String,
    pub production_environment: bool,
    pub transient_environment: bool,
    pub original_environment: String,
    pub statuses_url: String,
    pub performed_via_github_app: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CheckRunEvent {
    pub id: i64,
    pub action: String,
    pub name: String,
    pub head_sha: String,
    pub status: String,
    pub conclusion: Option<String>,
    pub started_at: DateTime<Utc>,
    pub completed_at: Option<DateTime<Utc>>,
    pub output_title: Option<String>,
    pub output_summary: Option<String>,
    pub output_text: Option<String>,
    pub output_annotations_count: i64,
    pub repository: String,
    pub app_name: String,
    pub check_suite_id: i64,
    pub details_url: Option<String>,
    pub external_id: Option<String>,
    pub pull_requests: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkflowRunEvent {
    pub id: i64,
    pub action: String,
    pub name: String,
    pub head_branch: String,
    pub head_sha: String,
    pub status: String,
    pub conclusion: Option<String>,
    pub workflow_id: i64,
    pub run_number: i64,
    pub run_attempt: i64,
    pub event: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub run_started_at: DateTime<Utc>,
    pub repository: String,
    pub triggering_actor: String,
    pub jobs_url: String,
    pub logs_url: String,
    pub artifacts_url: String,
    pub cancel_url: String,
    pub rerun_url: String,
    pub pull_requests: Vec<serde_json::Value>,
    pub referenced_workflows: Vec<serde_json::Value>,
    pub path: String,
    pub display_title: String,
}
