use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogEvent {
    pub id: String,
    pub timestamp: DateTime<Utc>,
    pub level: String,
    pub message: String,
    pub logger_name: String,
    pub thread_name: Option<String>,
    pub thread_id: Option<i64>,
    pub process_id: i64,
    pub hostname: String,
    pub service_name: String,
    pub service_version: Option<String>,
    pub environment: String,
    pub trace_id: Option<String>,
    pub span_id: Option<String>,
    pub parent_span_id: Option<String>,
    pub file_name: Option<String>,
    pub line_number: Option<i64>,
    pub function_name: Option<String>,
    pub stack_trace: Option<String>,
    pub exception_type: Option<String>,
    pub exception_message: Option<String>,
    pub tags: HashMap<String, String>,
    pub structured_data: HashMap<String, serde_json::Value>,
    pub facility: Option<String>,
    pub severity_number: i64,
    pub observed_timestamp: DateTime<Utc>,
    pub resource_attributes: HashMap<String, serde_json::Value>,
    pub log_attributes: HashMap<String, serde_json::Value>,
    pub body_bytes: Option<i64>,
    pub dropped_attributes_count: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraceSpanEvent {
    pub trace_id: String,
    pub span_id: String,
    pub parent_span_id: Option<String>,
    pub operation_name: String,
    pub service_name: String,
    pub service_version: Option<String>,
    pub span_kind: String,
    pub start_time: DateTime<Utc>,
    pub end_time: DateTime<Utc>,
    pub duration_ns: i64,
    pub status_code: String,
    pub status_message: Option<String>,
    pub attributes: HashMap<String, serde_json::Value>,
    pub events: Vec<serde_json::Value>,
    pub links: Vec<serde_json::Value>,
    pub resource_attributes: HashMap<String, serde_json::Value>,
    pub instrumentation_library: String,
    pub instrumentation_version: Option<String>,
    pub hostname: String,
    pub environment: String,
    pub http_method: Option<String>,
    pub http_url: Option<String>,
    pub http_status_code: Option<i64>,
    pub http_request_content_length: Option<i64>,
    pub http_response_content_length: Option<i64>,
    pub db_system: Option<String>,
    pub db_statement: Option<String>,
    pub rpc_system: Option<String>,
    pub rpc_service: Option<String>,
    pub rpc_method: Option<String>,
    pub net_peer_name: Option<String>,
    pub net_peer_port: Option<i64>,
    pub error: bool,
    pub dropped_attributes_count: i64,
    pub dropped_events_count: i64,
    pub dropped_links_count: i64,
    pub sampling_priority: Option<f64>,
    pub tags: HashMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricDatapointEvent {
    pub id: String,
    pub metric_name: String,
    pub metric_type: String,
    pub namespace: String,
    pub description: Option<String>,
    pub unit: String,
    pub timestamp: DateTime<Utc>,
    pub value: f64,
    pub count: i64,
    pub sum: f64,
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub quantile_values: HashMap<String, f64>,
    pub exemplars: Vec<serde_json::Value>,
    pub start_time: Option<DateTime<Utc>>,
    pub is_monotonic: bool,
    pub aggregation_temporality: String,
    pub hostname: String,
    pub service_name: String,
    pub environment: String,
    pub region: String,
    pub dimensions: HashMap<String, String>,
    pub resource_attributes: HashMap<String, serde_json::Value>,
    pub scope_name: Option<String>,
    pub scope_version: Option<String>,
    pub tags: HashMap<String, String>,
    pub histogram_bucket_counts: Vec<i64>,
    pub histogram_bucket_boundaries: Vec<f64>,
    pub flags: i64,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncidentEvent {
    pub id: String,
    pub incident_number: i64,
    pub title: String,
    pub description: Option<String>,
    pub status: String,
    pub severity: String,
    pub priority: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub resolved_at: Option<DateTime<Utc>>,
    pub acknowledged_at: Option<DateTime<Utc>>,
    pub detected_at: Option<DateTime<Utc>>,
    pub mitigated_at: Option<DateTime<Utc>>,
    pub commander: Option<String>,
    pub responders: Vec<String>,
    pub affected_services: Vec<String>,
    pub affected_environments: Vec<String>,
    pub impact_level: String,
    pub customer_impact: bool,
    pub customer_impact_duration_minutes: Option<i64>,
    pub action_items: Vec<serde_json::Value>,
    pub timeline_events: Vec<serde_json::Value>,
    pub postmortem_url: Option<String>,
    pub slack_channel: Option<String>,
    pub conference_bridge: Option<String>,
    pub tags: HashMap<String, String>,
    pub labels: Vec<String>,
    pub custom_fields: HashMap<String, serde_json::Value>,
    pub related_incidents: Vec<String>,
    pub source_alerts: Vec<String>,
    pub duration_seconds: Option<i64>,
    pub time_to_detect_seconds: Option<i64>,
    pub time_to_resolve_seconds: Option<i64>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PagerDutyAlertEvent {
    pub id: String,
    pub incident_key: String,
    pub service_id: String,
    pub service_name: String,
    pub escalation_policy_id: String,
    pub escalation_policy_name: String,
    pub urgency: String,
    pub status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub resolved_at: Option<DateTime<Utc>>,
    pub acknowledged_at: Option<DateTime<Utc>>,
    pub last_status_change_at: DateTime<Utc>,
    pub last_status_change_by: Option<String>,
    pub assigned_to: Vec<String>,
    pub acknowledged_by: Vec<String>,
    pub resolved_by: Option<String>,
    pub title: String,
    pub description: Option<String>,
    pub details: HashMap<String, serde_json::Value>,
    pub trigger_summary: Option<String>,
    pub trigger_type: String,
    pub alert_count: i64,
    pub is_mergeable: bool,
    pub incident_number: i64,
    pub html_url: String,
    pub conference_bridge: Option<serde_json::Value>,
    pub priority: Option<serde_json::Value>,
    pub teams: Vec<serde_json::Value>,
    pub pending_actions: Vec<serde_json::Value>,
    pub acknowledgements: Vec<serde_json::Value>,
    pub integration_name: Option<String>,
    pub integration_type: Option<String>,
    pub tags: HashMap<String, String>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GrafanaAlertEvent {
    pub id: String,
    pub alert_id: i64,
    pub dashboard_id: i64,
    pub panel_id: i64,
    pub org_id: i64,
    pub rule_name: String,
    pub rule_url: String,
    pub state: String,
    pub previous_state: String,
    pub new_state_date: DateTime<Utc>,
    pub eval_date: DateTime<Utc>,
    pub eval_data: Option<serde_json::Value>,
    pub execution_error: Option<String>,
    pub message: Option<String>,
    pub title: String,
    pub conditions: Vec<serde_json::Value>,
    pub frequency_seconds: i64,
    pub handler: i64,
    pub severity: String,
    pub silenced: bool,
    pub no_data_state: String,
    pub execution_error_state: String,
    pub for_duration: Option<String>,
    pub dashboard_slug: Option<String>,
    pub dashboard_uid: String,
    pub panel_url: Option<String>,
    pub image_url: Option<String>,
    pub tags: HashMap<String, String>,
    pub labels: HashMap<String, String>,
    pub annotations: HashMap<String, String>,
    pub values: HashMap<String, f64>,
    pub folder_title: Option<String>,
    pub notification_channels: Vec<String>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DatadogEvent {
    pub id: String,
    pub title: String,
    pub text: String,
    pub date_happened: DateTime<Utc>,
    pub priority: String,
    pub host: String,
    pub device_name: Option<String>,
    pub alert_type: String,
    pub source_type_name: String,
    pub aggregation_key: Option<String>,
    pub related_event_id: Option<i64>,
    pub tags: Vec<String>,
    pub url: Option<String>,
    pub is_aggregate: bool,
    pub children: Vec<serde_json::Value>,
    pub comments: Vec<String>,
    pub resource: Option<String>,
    pub monitor_id: Option<i64>,
    pub monitor_groups: Vec<String>,
    pub transition: Option<String>,
    pub event_object: Option<String>,
    pub org_id: i64,
    pub org_name: String,
    pub multi: bool,
    pub ci_level: Option<String>,
    pub last_updated: DateTime<Utc>,
    pub payload: Option<serde_json::Value>,
    pub metadata: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SentryErrorEvent {
    pub event_id: String,
    pub project_id: i64,
    pub project_slug: String,
    pub organization_slug: String,
    pub platform: String,
    pub level: String,
    pub logger: Option<String>,
    pub transaction: Option<String>,
    pub server_name: Option<String>,
    pub release: Option<String>,
    pub dist: Option<String>,
    pub environment: String,
    pub timestamp: DateTime<Utc>,
    pub received: DateTime<Utc>,
    pub title: String,
    pub message: Option<String>,
    pub culprit: Option<String>,
    pub exception_type: Option<String>,
    pub exception_value: Option<String>,
    pub exception_mechanism: Option<serde_json::Value>,
    pub stacktrace_frames: Vec<serde_json::Value>,
    pub tags: HashMap<String, String>,
    pub contexts: HashMap<String, serde_json::Value>,
    pub extra: HashMap<String, serde_json::Value>,
    pub fingerprint: Vec<String>,
    pub breadcrumbs: Vec<serde_json::Value>,
    pub request_url: Option<String>,
    pub request_method: Option<String>,
    pub request_headers: HashMap<String, String>,
    pub user_id: Option<String>,
    pub user_email: Option<String>,
    pub user_ip: Option<String>,
    pub user_username: Option<String>,
    pub sdk_name: String,
    pub sdk_version: String,
    pub is_unhandled: bool,
    pub group_id: Option<i64>,
    pub issue_url: Option<String>,
    pub metadata: HashMap<String, serde_json::Value>,
}
