use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentEvent {
    pub id: String,
    pub object: String,
    pub amount: i64,
    pub amount_received: i64,
    pub currency: String,
    pub customer: Option<String>,
    pub description: Option<String>,
    pub status: String,
    pub payment_method: String,
    pub payment_method_types: Vec<String>,
    pub created: DateTime<Utc>,
    pub livemode: bool,
    pub metadata: HashMap<String, String>,
    pub receipt_email: Option<String>,
    pub statement_descriptor: Option<String>,
    pub capture_method: String,
    pub confirmation_method: String,
    pub client_secret: Option<String>,
    pub last_payment_error: Option<serde_json::Value>,
    pub next_action: Option<serde_json::Value>,
    pub shipping: Option<serde_json::Value>,
    pub charges: Vec<serde_json::Value>,
    pub application_fee_amount: Option<i64>,
    pub transfer_data: Option<serde_json::Value>,
    pub on_behalf_of: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceEvent {
    pub id: String,
    pub object: String,
    pub account_name: Option<String>,
    pub amount_due: i64,
    pub amount_paid: i64,
    pub amount_remaining: i64,
    pub currency: String,
    pub customer: String,
    pub customer_email: Option<String>,
    pub customer_name: Option<String>,
    pub description: Option<String>,
    pub status: String,
    pub subscription: Option<String>,
    pub created: DateTime<Utc>,
    pub due_date: Option<DateTime<Utc>>,
    pub period_start: DateTime<Utc>,
    pub period_end: DateTime<Utc>,
    pub lines: Vec<serde_json::Value>,
    pub livemode: bool,
    pub metadata: HashMap<String, String>,
    pub paid: bool,
    pub attempted: bool,
    pub attempt_count: i64,
    pub auto_advance: bool,
    pub billing_reason: Option<String>,
    pub collection_method: String,
    pub hosted_invoice_url: Option<String>,
    pub invoice_pdf: Option<String>,
    pub number: Option<String>,
    pub subtotal: i64,
    pub tax: Option<i64>,
    pub total: i64,
    pub total_discount_amounts: Vec<serde_json::Value>,
    pub total_tax_amounts: Vec<serde_json::Value>,
    pub webhooks_delivered_at: Option<DateTime<Utc>>,
    pub default_payment_method: Option<String>,
    pub effective_at: Option<DateTime<Utc>>,
    pub footer: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionEvent {
    pub id: String,
    pub object: String,
    pub customer: String,
    pub status: String,
    pub plan_id: String,
    pub plan_amount: i64,
    pub plan_currency: String,
    pub plan_interval: String,
    pub plan_interval_count: i64,
    pub current_period_start: DateTime<Utc>,
    pub current_period_end: DateTime<Utc>,
    pub cancel_at_period_end: bool,
    pub canceled_at: Option<DateTime<Utc>>,
    pub ended_at: Option<DateTime<Utc>>,
    pub created: DateTime<Utc>,
    pub trial_start: Option<DateTime<Utc>>,
    pub trial_end: Option<DateTime<Utc>>,
    pub livemode: bool,
    pub metadata: HashMap<String, String>,
    pub items: Vec<serde_json::Value>,
    pub default_payment_method: Option<String>,
    pub latest_invoice: Option<String>,
    pub pending_setup_intent: Option<String>,
    pub collection_method: String,
    pub billing_cycle_anchor: DateTime<Utc>,
    pub application_fee_percent: Option<f64>,
    pub discount: Option<serde_json::Value>,
    pub quantity: i64,
    pub days_until_due: Option<i64>,
    pub start_date: DateTime<Utc>,
    pub schedule: Option<String>,
    pub test_clock: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefundEvent {
    pub id: String,
    pub object: String,
    pub amount: i64,
    pub currency: String,
    pub charge: String,
    pub payment_intent: Option<String>,
    pub reason: Option<String>,
    pub status: String,
    pub created: DateTime<Utc>,
    pub receipt_number: Option<String>,
    pub balance_transaction: Option<String>,
    pub metadata: HashMap<String, String>,
    pub source_transfer_reversal: Option<String>,
    pub transfer_reversal: Option<String>,
    pub failure_balance_transaction: Option<String>,
    pub failure_reason: Option<String>,
    pub instructions_email: Option<String>,
    pub destination_details: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DisputeEvent {
    pub id: String,
    pub object: String,
    pub amount: i64,
    pub currency: String,
    pub charge: String,
    pub payment_intent: Option<String>,
    pub reason: String,
    pub status: String,
    pub created: DateTime<Utc>,
    pub evidence_due_by: DateTime<Utc>,
    pub is_charge_refundable: bool,
    pub livemode: bool,
    pub metadata: HashMap<String, String>,
    pub balance_transactions: Vec<serde_json::Value>,
    pub evidence: serde_json::Value,
    pub evidence_details: serde_json::Value,
    pub network_reason_code: Option<String>,
    pub payment_method_details: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChargeEvent {
    pub id: String,
    pub object: String,
    pub amount: i64,
    pub amount_captured: i64,
    pub amount_refunded: i64,
    pub currency: String,
    pub customer: Option<String>,
    pub description: Option<String>,
    pub status: String,
    pub paid: bool,
    pub captured: bool,
    pub refunded: bool,
    pub disputed: bool,
    pub created: DateTime<Utc>,
    pub livemode: bool,
    pub metadata: HashMap<String, String>,
    pub payment_intent: Option<String>,
    pub payment_method: Option<String>,
    pub receipt_email: Option<String>,
    pub receipt_url: Option<String>,
    pub balance_transaction: Option<String>,
    pub billing_details: serde_json::Value,
    pub outcome: Option<serde_json::Value>,
    pub fraud_details: Option<serde_json::Value>,
    pub source: Option<serde_json::Value>,
    pub statement_descriptor: Option<String>,
    pub statement_descriptor_suffix: Option<String>,
    pub transfer_data: Option<serde_json::Value>,
    pub transfer_group: Option<String>,
    pub application_fee: Option<String>,
    pub application_fee_amount: Option<i64>,
    pub failure_code: Option<String>,
    pub failure_message: Option<String>,
    pub on_behalf_of: Option<String>,
    pub shipping: Option<serde_json::Value>,
    pub calculated_statement_descriptor: Option<String>,
}
